=== nginx/unit/docs/changes.dtd
<!ENTITY  nbsp         "&#xA0;" >
<!ENTITY  mdash        "&#xA0;- " >


<!ELEMENT change_log   (changes)* >
<!ATTLIST change_log   title  CDATA #REQUIRED >

<!ELEMENT changes      (change)* >
<!ATTLIST changes      ver      CDATA #REQUIRED
                       rev      CDATA #REQUIRED
                       date     CDATA #REQUIRED
                       time     CDATA #REQUIRED
                       packager CDATA #REQUIRED
                       apply    CDATA #REQUIRED
>

<!ELEMENT change       (para)* >
<!ATTLIST change       type (bugfix | feature | change | security | workaround) #IMPLIED >

<!ELEMENT para         (#PCDATA | at | br | nobr)* >

<!ELEMENT at           EMPTY >
<!ELEMENT br           EMPTY >
<!ELEMENT nobr         (#PCDATA) >

=== nginx/unit/docs/changes.xml
<?xml version="1.0" ?>
<!DOCTYPE change_log SYSTEM "changes.dtd" >


<change_log title="unit">


<changes apply="unit-php
                unit-python unit-python2.7
                unit-python3.4 unit-python3.5 unit-python3.6 unit-python3.7
                unit-python3.8 unit-python3.9 unit-python3.10 unit-python3.11
                unit-python3.12
                unit-go
                unit-perl
                unit-ruby
                unit-jsc-common unit-jsc8 unit-jsc10 unit-jsc11 unit-jsc13
                unit-jsc14 unit-jsc15 unit-jsc16 unit-jsc17 unit-jsc18
                unit-jsc19 unit-jsc20 unit-jsc21
                unit-wasm"
         ver="1.34.0" rev="1"
         date="2024-12-19" time="18:00:00 +0000"
         packager="Nginx Packaging &lt;nginx-packaging@f5.com&gt;">

<change>
<para>
NGINX Unit updated to 1.34.0.
</para>
</change>

</changes>


<changes apply="unit" ver="1.34.0" rev="1"
         date="2024-12-19" time="18:00:00 +0000"
         packager="Nginx Packaging &lt;nginx-packaging@f5.com&gt;">

<change type="feature">
<para>
initial OpenTelemetry (OTEL) support.
</para>
</change>

<change type="feature">
<para>
support for JSON formatted access logs.
</para>
</change>

<change type="bugfix">
<para>
tweak the Perl language module to avoid breaking scripts in some
circumstances.
</para>
</change>

</changes>


<changes apply="unit-php
                unit-python unit-python2.7
                unit-python3.4 unit-python3.5 unit-python3.6 unit-python3.7
                unit-python3.8 unit-python3.9 unit-python3.10 unit-python3.11
                unit-python3.12
                unit-go
                unit-perl
                unit-ruby
                unit-jsc-common unit-jsc8 unit-jsc10 unit-jsc11 unit-jsc13
                unit-jsc14 unit-jsc15 unit-jsc16 unit-jsc17 unit-jsc18
                unit-jsc19 unit-jsc20 unit-jsc21
                unit-wasm"
         ver="1.33.0" rev="1"
         date="2024-09-17" time="18:00:00 +0000"
         packager="Nginx Packaging &lt;nginx-packaging@f5.com&gt;">

<change>
<para>
NGINX Unit updated to 1.33.0.
</para>
</change>

</changes>


<changes apply="unit" ver="1.33.0" rev="1"
         date="2024-09-17" time="18:00:00 +0000"
         packager="Nginx Packaging &lt;nginx-packaging@f5.com&gt;">

<change type="feature">
<para>
make the number of router threads configurable.
</para>
</change>

<change type="feature">
<para>
make the listen(2) backlog configurable.
</para>
</change>

<change type="feature">
<para>
add Python application factory support.
</para>
</change>

<change type="feature">
<para>
add experimental chunked request body support. (Disabled by default).
</para>
</change>

<change type="feature">
<para>
add fuzzing via oss-fuzz.
</para>
</change>

<change type="feature">
<para>
add "if" option to the "match" object.
</para>
</change>

<change type="feature">
<para>
show list of loaded language modules in the /status endpoint.
</para>
</change>

<change type="feature">
<para>
Unit ships with a new Rust based CLI application "unitctl".
</para>
</change>

<change type="feature">
<para>
the wasm-wasi-component language module now inherits the processes
environment.
</para>
</change>

<change type="change">
<para>
under systemd unit runs in forking mode (once again).
</para>
</change>

<change type="change">
<para>
if building with njs, version 0.8.3 or later is now required.
</para>
</change>

<change type="change">
<para>
Unit now builds with -std=gnu11 (C11 with GNU extensions).
</para>
</change>

<change type="change">
<para>
Unit now creates the full directory path for the PID file and control socket.
</para>
</change>

<change type="change">
<para>
build system improvements, including pretty printing the make output and
enabling various make variables to influence the build process (see:
make help).
</para>
</change>

<change type="change">
<para>
better detection of available runnable CPUs on Linux.
</para>
</change>

<change type="change">
<para>
default listen(2) backlog on Linux now defaults to Kernel default.
</para>
</change>

<change type="bugfix">
<para>
don't modify REQUEST_URI.
</para>
</change>

<change type="bugfix">
<para>
fix a crash when interrupting a download via a proxy.
</para>
</change>

<change type="bugfix">
<para>
wasm-wasi-component application process hangs after receiving restart signal
from the control endpoint.
</para>
</change>

<change type="bugfix">
<para>
njs variables accessed with a JS template literal should not be cacheable.
</para>
</change>

<change type="bugfix">
<para>
properly handle deleting arrays of certificates.
</para>
</change>

<change type="bugfix">
<para>
don't create the $runstatedir directory which triggered an Alpine packaging
error.
</para>
</change>

</changes>


<changes apply="unit-jsc21" ver="1.32.0" rev="1"
         date="2023-10-17" time="16:00:00 -0700"
         packager="Nginx Packaging &lt;nginx-packaging@f5.com&gt;">

<change>
<para>
Initial release of Java 21 module for NGINX Unit.
</para>
</change>

</changes>


<changes apply="unit-python3.12" ver="1.32.0" rev="1"
         date="2023-10-17" time="16:00:00 -0700"
         packager="Nginx Packaging &lt;nginx-packaging@f5.com&gt;">

<change>
<para>
Initial release of Python 3.12 module for NGINX Unit.
</para>
</change>

</changes>


<changes apply="unit-php
                unit-python unit-python2.7
                unit-python3.4 unit-python3.5 unit-python3.6 unit-python3.7
                unit-python3.8 unit-python3.9 unit-python3.10 unit-python3.11
                unit-python3.12
                unit-go
                unit-perl
                unit-ruby
                unit-jsc-common unit-jsc8 unit-jsc10 unit-jsc11 unit-jsc13
                unit-jsc14 unit-jsc15 unit-jsc16 unit-jsc17 unit-jsc18
                unit-jsc19 unit-jsc20 unit-jsc21
                unit-wasm"
         ver="1.32.0" rev="1"
         date="2024-02-27" time="18:00:00 +0000"
         packager="Nginx Packaging &lt;nginx-packaging@f5.com&gt;">

<change>
<para>
NGINX Unit updated to 1.32.0.
</para>
</change>


</changes>


<changes apply="unit" ver="1.32.0" rev="1"
         date="2024-02-27" time="18:00:00 +0000"
         packager="Nginx Packaging &lt;nginx-packaging@f5.com&gt;">

<change type="feature">
<para>
WebAssembly Components using WASI interfaces defined in wasi:http/proxy@0.2.0.
</para>
</change>

<change type="feature">
<para>
conditional access logging.
</para>
</change>

<change type="feature">
<para>
njs variables access.
</para>
</change>

<change type="feature">
<para>
$request_id variable contains a string that is formed using random data and
can be used as a unique request identifier.
</para>
</change>

<change type="feature">
<para>
options to set control socket permissions.
</para>
</change>

<change type="feature">
<para>
Ruby arrays in response headers, improving compatibility with Rack v3.0.
</para>
</change>

<change type="feature">
<para>
Python bytearray response bodies for ASGI applications.
</para>
</change>

<change type="bugfix">
<para>
router could crash while sending large files. Thanks to rustedsword.
</para>
</change>

<change type="bugfix">
<para>
serving static files from a network filesystem could lead to error.
</para>
</change>

<change type="bugfix">
<para>
"uidmap" and "gidmap" isolation options validation.
</para>
</change>

<change type="bugfix">
<para>
abstract UNIX socket name could be corrupted during configuration validation.
Thanks to Alejandro Colomar.
</para>
</change>

<change type="bugfix">
<para>
HTTP header field value encoding could be misinterpreted in Python module.
</para>
</change>

<change type="bugfix">
<para>
Node.js http.createServer() accepts and ignores the "options" argument,
improving compatibility with strapi applications, among others.
</para>
</change>

<change type="bugfix">
<para>
ServerRequest.flushHeaders() implemented in Node.js module to make it compatible
with Next.js.
</para>
</change>

<change type="bugfix">
<para>
ServerRequest.httpVersion variable format in Node.js module.
</para>
</change>

<change type="bugfix">
<para>
Node.js module handles standard library imports prefixed with "node:", making it
possible to run newer Nuxt applications, among others.
</para>
</change>

<change type="bugfix">
<para>
Node.js tarball location changed to avoid build/install errors.
</para>
</change>

<change type="bugfix">
<para>
Go module sets environment variables necessary for building on macOS/arm64
systems.
</para>
</change>

</changes>

<changes apply="unit-php
                unit-python unit-python2.7
                unit-python3.4 unit-python3.5 unit-python3.6 unit-python3.7
                unit-python3.8 unit-python3.9 unit-python3.10 unit-python3.11
                unit-go
                unit-perl
                unit-ruby
                unit-jsc-common unit-jsc8 unit-jsc10 unit-jsc11 unit-jsc13
                unit-jsc14 unit-jsc15 unit-jsc16 unit-jsc17 unit-jsc18
                unit-jsc19 unit-jsc20
                unit-wasm"
         ver="1.31.1" rev="1"
         date="2023-10-19" time="18:00:00 +0300"
         packager="Nginx Packaging &lt;nginx-packaging@f5.com&gt;">

<change>
<para>
NGINX Unit updated to 1.31.1.
</para>
</change>

</changes>


<changes apply="unit" ver="1.31.1" rev="1"
         date="2023-10-19" time="18:00:00 +0300"
         packager="Nginx Packaging &lt;nginx-packaging@f5.com&gt;">

<change type="feature">
<para>
allow to set the HTTP response status in Wasm module.
</para>
</change>

<change type="feature">
<para>
allow uploads larger than 4GiB in Wasm module.
</para>
</change>

<change type="bugfix">
<para>
application process could crash while rewriting URLs with query strings.
</para>
</change>

<change type="bugfix">
<para>
requests larger than about 64MiB could cause error in Wasm module.
</para>
</change>

<change type="bugfix">
<para>
when using many headers in Java module some of them could be
corrupted due to memory realocation issue.
