=== nginx/unit/docs/change_log_conf.dtd
<!ELEMENT configuration   (generic, rpm, deb, changes+) >

<!ELEMENT generic         (length, start, indent?) >
<!ELEMENT rpm             (length, start, indent?) >
<!ELEMENT deb             (length, start, indent?) >

<!ELEMENT length          (#PCDATA) >
<!ELEMENT start           (#PCDATA) >
<!ELEMENT indent          (#PCDATA) >

<!ELEMENT changes         (title, length,
                           bugfix, feature, change, security, workaround,
                           (month, month, month, month, month, month,
                            month, month, month, month, month, month),
                           (day, day, day, day, day, day, day)?) >

<!ELEMENT title           (#PCDATA) >

<!ELEMENT bugfix          (#PCDATA) >
<!ELEMENT feature         (#PCDATA) >
<!ELEMENT change          (#PCDATA) >
<!ELEMENT security        (#PCDATA) >
<!ELEMENT workaround      (#PCDATA) >

<!ELEMENT month           (#PCDATA) >
<!ELEMENT day             (#PCDATA) >

=== nginx/unit/docs/change_log_conf.xml
<?xml version="1.0" ?>
<!DOCTYPE configuration SYSTEM "change_log_conf.dtd" >

<configuration>

<generic>
<length>76</length>
<start>    *) </start>
<indent>       </indent>
</generic>

<rpm>
<length>76</length>
<start>- </start>
<indent>  </indent>
</rpm>

<deb>
<length>76</length>
<start>  * </start>
<indent>    </indent>
</deb>

<changes>
    <title>Changes with </title>
    <length>65</length>

    <bugfix>Bugfix</bugfix>
    <feature>Feature</feature>
    <change>Change</change>
    <security>Security</security>
    <workaround>Workaround</workaround>

    <month> Jan </month>
    <month> Feb </month>
    <month> Mar </month>
    <month> Apr </month>
    <month> May </month>
    <month> Jun </month>
    <month> Jul </month>
    <month> Aug </month>
    <month> Sep </month>
    <month> Oct </month>
    <month> Nov </month>
    <month> Dec </month>

    <day>Sun</day>
    <day>Mon</day>
    <day>Tue</day>
    <day>Wed</day>
    <day>Thu</day>
    <day>Fri</day>
    <day>Sat</day>
</changes>

</configuration>
